### ISSUE TITLE
Error when reading knx object

### ISSUE THREAD

**Issue by vervaekejonathan** [fma38/pKNyX#1]
$python pknyx-group.py read 0/0/1
gives me the following traceback:

> UDPTransceiver._receiverLoop()
> Traceback (most recent call last):
>   File "/home/jonathan/.local/lib/python2.7/site-packages/pknyx/stack/transceiver/udpTransceiver.py", line 159, in _receiverLoop
>     cEMI = CEMILData(frame)
>   File "/home/jonathan/.local/lib/python2.7/site-packages/pknyx/stack/cemi/cemiLData.py", line 109, in __init__
>     self._frame = CEMILDataFrame(frame)
>   File "/home/jonathan/.local/lib/python2.7/site-packages/pknyx/stack/cemi/cemiLDataFrame.py", line 110, in __init__
>     raise CEMIValueError("data too short (%d)" % len(frame))
> CEMIValueError: data too short (8)

> Traceback (most recent call last):
>   File "pknyx-group.py", line 397, in <module>
>     main()
>   File "pknyx-group.py", line 393, in main
>     args.func(**options)
>   File "pknyx-group.py", line 243, in read
>     value = dptXlator.dataToValue(dptXlator.frameToData(data))
>   File "/home/jonathan/.local/lib/python2.7/site-packages/pknyx/core/dptXlator/dptXlatorBoolean.py", line 129, in dataToValue
>     value = self._dpt.limits[data]
> IndexError: tuple index out of range
> 

i have set up eibd with the following command:

> eibd -D -T -R -S -i -u usb:1:9:1:0:0

ps:

> eibd -t65535 -i usb:1:9:1:0:0 

works (in the way that it logs the knx objects send to the knx usb interface)

**Comment by fma38** [comment]
Does it happen every time? Does it happen with read on other GAD? Could you try to launch the command in full trace mode and report the output?

`$ pknyx-group.py -l trace read 0/0/1`

Thanks.

**Comment by vervaekejonathan** [comment]
This does not happen every time. 

> MainThread::A_GroupDataService.subscribe(): gad=0/0/1, listener=<__main__.SimpleGroupObject object at 0x7fa26f15a690>
> MainThread::Stack.start()
> LinkLayer::L_DataService.run()
> MainThread::UDPTransceiver.start()
> UDP receiver::UDPTransceiver._receiverLoop()
> UDP transmitter::UDPTransceiver._transmitterLoop()
> MainThread::Stack.start(): initiate a read request for Group having at least one GroupObject with 'init' flag on
> MainThread::Stack.start(): listener does not seem to be a GroupObject
> Traceback (most recent call last):
>   File "/home/jonathan/.local/lib/python2.7/site-packages/pknyx/stack/stack.py", line 130, in start
>     if listener.flags.init:
> AttributeError: 'SimpleGroupObject' object has no attribute 'flags'
> MainThread::Stack.start(): running
> MainThread::A_GroupDataService.groupValueReadReq(): gad=0/0/1, priority=low
> MainThread::T_GroupDataService.groupDataReq(): gad=0/0/1, priority=low, tSDU=bytearray(b'\x00\x00')
> MainThread::N_GroupDataService.groupDataReq(): gad=0/0/1, priority=low, nSDU=bytearray(b'\x00\x00')
> MainThread::L_DataService.dataReq(): cEMI=<CEMILData(mc=0x29, priority=low, src=0.0.0, dest=0/0/1, npdu=bytearray(b'\x01\x00\x00'))>
> UDP transmitter::UDPTransceiver._transmitterLoop(): transmission=<Transmission(payload=<CEMILDataFrame(mc=0x29, addIL=0, ctrl1=0xbc, ctrl2=0xe0, src=0x0, dest=0x1)>, waitConfirm=True, result=0)>
> UDP transmitter::UDPTransceiver._transmitterLoop(): frame= bytearray(b'\x06\x10\x050\x00\x11)\x00\xbc\xe0\x00\x00\x00\x01\x01\x00\x00')
> UDP transmitter::UDPTransceiver._transmitterLoop(): transmission=<Transmission(payload=<CEMILDataFrame(mc=0x29, addIL=0, ctrl1=0xbc, ctrl2=0xe0, src=0x0, dest=0x1)>, waitConfirm=False, result=0)>
> UDP receiver::UDPTransceiver._receiverLoop(): inFrame='\x06\x10\x050\x00\x11)\x00\xbc\xe0\x00\x00\x00\x01\x01\x00\x00' (127.0.1.1, 3671)
> UDP receiver::UDPTransceiver._receiverLoop(): KNXnetIP header=<KNXnetIPHeader(service='routing.ind', totalSize=17)>
> UDP receiver::UDPTransceiver._receiverLoop(): frame=bytearray(b')\x00\xbc\xe0\x00\x00\x00\x01\x01\x00\x00')
> UDP receiver::UDPTransceiver._receiverLoop(): cEMI=<CEMILData(mc=0x29, priority=low, src=0.0.0, dest=0/0/1, npdu=bytearray(b'\x01\x00\x00'))>
> UDP receiver::L_DataService.putInFrame(): cEMI=<CEMILData(mc=0x29, priority=low, src=0.0.0, dest=0/0/1, npdu=bytearray(b'\x01\x00\x00'))>
> LinkLayer::L_DataService.run(): cEMI=<CEMILData(mc=0x29, priority=low, src=0.0.0, dest=0/0/1, npdu=bytearray(b'\x01\x00\x00'))>
> UDP receiver::UDPTransceiver._receiverLoop(): inFrame='\x06\x10\x050\x00\x12)\x00\xbc\xd0\x11\x01\x00\x01\x02\x00@\x06' (10.0.209.116, 3671)
> UDP receiver::UDPTransceiver._receiverLoop(): KNXnetIP header=<KNXnetIPHeader(service='routing.ind', totalSize=18)>
> UDP receiver::UDPTransceiver._receiverLoop(): frame=bytearray(b')\x00\xbc\xd0\x11\x01\x00\x01\x02\x00@\x06')
> UDP receiver::UDPTransceiver._receiverLoop(): cEMI=<CEMILData(mc=0x29, priority=low, src=1.1.1, dest=0/0/1, npdu=bytearray(b'\x02\x00@\x06'))>
> UDP receiver::L_DataService.putInFrame(): cEMI=<CEMILData(mc=0x29, priority=low, src=1.1.1, dest=0/0/1, npdu=bytearray(b'\x02\x00@\x06'))>
> LinkLayer::L_DataService.run(): cEMI=<CEMILData(mc=0x29, priority=low, src=1.1.1, dest=0/0/1, npdu=bytearray(b'\x02\x00@\x06'))>
> LinkLayer::N_GroupDataService.dataInd(): cEMI=<CEMILData(mc=0x29, priority=<Priority('low')>, src=<IndividualAddress('1.1.1')>, dest=<GroupAddress('0/0/1')>, npdu=bytearray(b'\x02\x00@\x06'))>
> LinkLayer::T_GroupDataService.groupDataInd(): src=1.1.1, gad=0/0/1, priority=low, tPDU=bytearray(b'\x00@\x06')
> LinkLayer::A_GroupDataService.groupDataInd(): src=1.1.1, gad=0/0/1, priority=low, aPDU=bytearray(b'\x00@\x06')
> LinkLayer::Group.groupValueReadCon(): src=1.1.1, priority=low, data=bytearray(b'\x06')
> LinkLayer::SimpleGroupObject.onResponse(): src=1.1.1, data=bytearray(b'\x06')
> MainThread::Stack.stop()
> MainThread::UDPTransceiver.stop()
> MainThread::L_DataService.stop()
> MainThread::UDPTransceiver.join()
> LinkLayer::L_DataService.run(): ended
> UDP transmitter::UDPTransceiver._transmitterLoop(): ended
> UDP receiver::UDPTransceiver._receiverLoop(): ended
> MainThread::Stack.stop(): stopped
> Traceback (most recent call last):
>   File "pknyx-group.py", line 399, in <module>
>     main()
>   File "pknyx-group.py", line 395, in main
>     args.func(**options)
>   File "pknyx-group.py", line 245, in read
>     value = dptXlator.dataToValue(dptXlator.frameToData(data))
>   File "/home/jonathan/.local/lib/python2.7/site-packages/pknyx/core/dptXlator/dptXlatorBoolean.py", line 129, in dataToValue
>     value = self._dpt.limits[data]
> IndexError: tuple index out of range
>

**Comment by vervaekejonathan** [comment]
i figured out this only happens when the return value is not 0 or 1. Possibly this function currently only works for bits (0/1). Same for the write function.

**Comment by fma38** [comment]
If the return value is not 0 or 1, this means that this is not a 1.xxx DPT object. So, you need to give the type:

`$ pknyx-group.py read 0/0/1 -d 9.xxx`

(I used 9.xxx as example).

Same for writing.

**Comment by vervaekejonathan** [comment]
That helps, thanks!
